### ISSUE TITLE
'FBSDKCoreKit' has a minimum deployment target of iOS 9.0

### ISSUE THREAD

**Issue by diegogarciar** [oddbit/flutter_facebook_app_events#64] opened 2020-11-17 17:40 UTC
I'm getting this error
Compiling for iOS 8.0, but module 'FBSDKCoreKit' has a minimum deployment target of iOS 9.0: 

## Expected Behavior
Build App

## Current Behavior
App not building 

## Possible Solution
Update facebook_app_events target to iOS 9.0

## Steps to Reproduce (for bugs)
update package to 0.8.1

* Operating System and version:
iPhone 12 mini, iOS 14.2 emulator

**Comment by chandrashan** [comment] 2020-11-17 21:59
if you are using Xcode - does changing the minimum deployment target using the instructions on the link below help:

https://www.avanderlee.com/workflow/minimum-ios-version/

**Comment by diegogarciar** [comment] 2020-11-17 22:01
Yes, I did that for the `facebook_app_events` target and it worked for now

<img width="864" alt="Screen Shot 2020-11-17 at 3 01 14 p m" src="https://user-images.githubusercontent.com/17276155/99455907-be48dc80-28e5-11eb-98a0-7adcaeda7094.png">

**Comment by DennisAlund** [comment] 2020-11-19 13:55
Hm, this is a strange behavior. Because I can see that you are also using Firebase plugins, and all the Flutter/Firebase plugins are also configured with ` s.ios.deployment_target = '8.0'` ... the same as this plugin: 

https://github.com/oddbit/flutter_facebook_app_events/blob/d150f96c43facc86b9dc1f33157df48c123d5d25/ios/facebook_app_events.podspec#L18

https://github.com/FirebaseExtended/flutterfire/search?q=deployment_target
[![image](https://user-images.githubusercontent.com/2051607/99675112-c81f3b00-2ab1-11eb-9040-296d45be03bd.png)](https://github.com/FirebaseExtended/flutterfire/search?q=deployment_target)

**Comment by DennisAlund** [comment] 2020-11-19 13:57
Could you confirm that the problem is solved by updating the `deployment_target` in this line (without the changes that you did in xcode)

https://github.com/oddbit/flutter_facebook_app_events/blob/d150f96c43facc86b9dc1f33157df48c123d5d25/ios/facebook_app_events.podspec#L18

Because I did not experience any issues locally on in my projects. So I'm just curious to find out how it is linked together. I am not very familiar with xcode and ios development in particular.

**Comment by diegogarciar** [comment] 2020-11-20 16:33
Yes I don't know how firebase can get away with that, but replacing that line and running pod install fixed the issue.

**Comment by DennisAlund** [comment] 2020-11-20 16:44
Okay, I can't reproduce the issue. So I'd like to see how we can consistently reproduce it both causing the error and making it go away by making this change. Because the screenshot change in your comment https://github.com/oddbit/flutter_facebook_app_events/issues/64#issuecomment-729240467 only shows changing in xcode.

Can you bring the error back and then, instead of changing in xcode, change the `s.ios.deployment_target = '9.0'` only in podspec. In other words, not accessing any configurations of the plugin through xcode. 

I'd like to see a strong connection between these two, since it doesn't cause error on my project and I can't reproduce it.

**Comment by diegogarciar** [comment] 2020-11-20 16:47
Yes that's what I did, I changed  
` s.ios.deployment_target = '9.0' `
ran pod install and that updated the line I was manually setting

**Comment by DennisAlund** [comment] 2020-11-20 16:57
Interesting. Let me try to understand it better and what the other effects or impact it will have to set the target to `9.0`. Just to make sure that it doesn't bring other incompatibilites for things that was working with `8.0`

**Comment by leonardocustodio** [comment] 2020-11-21 22:48
I'm having the same issue. And well it does work fine changing the deployment target on xcode.
But we use CI/CD for our projects and that's an issue because since it clones the project and it starts the whole pod install thing the deployment target will was be set as 8.0. I did change the script of Podfile for setting to 9.0 (ps.: just setting the platform will not fix, gotta change on a post_install script) but if flutter updates the base Podfile template for some reason it could give us some issues.

**Comment by DennisAlund** [comment] 2020-11-22 08:37
If it's okay with you guys, I will first change the dependency to `9.0` on a local copy of the plugin and run with our existing projects to see if there seem to be any side-effects.

Because my concern is that **it does work for me** (famous last words). So if having `8.0` works for me, I'm interested to see if changing it to `9.0` makes something **not work for me**. 

So if you give me a bit of time to test things out with the different configurations to ensure there aren't any surprises.

**Comment by leonardocustodio** [comment] 2020-11-23 14:33
Sure @DennisAlund no problem, if you need help to test it out, just let us know.

**Comment by yelkamel** [comment] 2020-11-28 22:00
I changed my local copy repo of this repo from 8 to 9 to be able to run.

**Comment by trueAtom** [comment] 2020-12-07 14:09
the same problem

**Comment by DennisAlund** [comment] 2020-12-11 01:45
Is this thread related to your issue: https://stackoverflow.com/questions/63973136/the-ios-deployment-target-iphoneos-deployment-target-is-set-to-8-0-in-flutter

Could you guys provide your `flutter doctor` output?

**Comment by trueAtom** [comment] 2020-12-14 10:38
> Is this thread related to your issue: https://stackoverflow.com/questions/63973136/the-ios-deployment-target-iphoneos-deployment-target-is-set-to-8-0-in-flutter

It helped, thanks

**Comment by DennisAlund** [comment] 2020-12-16 01:40
Happy to hear that :-) 

I'll close the issue for now and feel free to discuss further if there was something else that wasn't addressed.

**Closed by DennisAlund** 2020-12-16 01:40 UTC

**Comment by RicardoRB** [comment] 2020-12-31 14:59
I have this problem when I build, I tried to change the version everywhere to 9.0 but it doesn't work

**Comment by theweiweiway** [comment] 2021-01-15 20:08
Yeah i followed https://stackoverflow.com/questions/63973136/the-ios-deployment-target-iphoneos-deployment-target-is-set-to-8-0-in-flutter too but i can't seem to get it working

The app builds and runs, but it immediately crashes upon starting up.

**Comment by diegogarciar** [comment] 2021-01-15 20:15
I think it would be easier to just bump the version to 9 as it is the right fix, I don't see a reason of why not change it if its not supported for those versions. 

> Yes I don't know how firebase can get away with that, but replacing that line and running pod install fixed the issue.

I find it extremely annoying to open Xcode just to change the setting each time I update other packages.

pd: FlutterFire [changed this setting](https://github.com/FirebaseExtended/flutterfire/blob/928202d95ccd4afffad3cbc92b70eb25b9f965d4/packages/firebase_messaging/firebase_messaging/ios/firebase_messaging.podspec#L31) too.
