### ISSUE TITLE
Crash while starting app

### ISSUE THREAD

**Issue by boyfox** [oddbit/flutter_facebook_app_events#13] opened 2019-12-06 17:16 UTC
Hi, when starting app on the android devices you will get crash after following log:
```
I/Process (11231): Sending signal. PID: 11231 SIG: 9
Lost connection to device.
Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:51944/UviuoMqg1ck=/
```

But works well on the iOS devices

**Comment by DennisAlund** [comment] 2019-12-10 16:12
Could you please clarify how the issue that you are facing has been traced down to be caused by this plugin.

**Comment by DennisAlund** [comment] 2019-12-14 05:39
Closing due to seemingly unrelated to the plug-in

**Closed by DennisAlund** 2019-12-14 05:39 UTC
