### ISSUE TITLE
Error when running flutter app with facebook_app_events plugged in

### ISSUE THREAD

**Issue by rowboater** [oddbit/flutter_facebook_app_events#63] opened 2020-11-16 14:17 UTC
I'm trying to use Facebook app events within my app and several investigative paths led me to this.

I'm following the installation and examples guides to using the application, but as soon as I install the app I get the following exception:
```
E/flutter (27977): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
E/flutter (27977):                
```                    

## Your Environment
* Output from `flutter doctor`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.3, on macOS 11.0.1 20B28, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
 
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3 Beta)
[✓] VS Code (version 1.51.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by DennisAlund** [comment] 2020-11-17 02:33
Duplicate of https://github.com/oddbit/flutter_facebook_app_events/issues/37

**Closed by DennisAlund** 2020-11-17 02:33 UTC
Labels: duplicate
