### ISSUE TITLE
[Bug]: Maven not found

### ISSUE THREAD

**Issue by amilkarSingular** [oddbit/flutter_facebook_app_events#264] opened 2022-10-30 16:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello i got a issue when i try to compile....the error is something like cannot reach https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml

neither of versions works (14,15+)....i used the first one buy today is not working.....after that i tried to cahnge to 15+ and still not working.....

can you confirm is problem about the central repository or package?

ERROR: (The error is the same with 15.+)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.facebook.android:facebook-android-sdk:14.+.
     Required by:
         project :app > project :facebook_app_events
      > Failed to list versions for com.facebook.android:facebook-android-sdk.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml'.
               > Read timed out

### Expected Behavior

Compile

### Steps To Reproduce

Just try tu running the app

### Platform

Android

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version    10.0.19044.2130], locale en-US)
    • Flutter version 3.3.2 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (7 weeks ago), 2022-09-14
      08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Amilkar\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.72.2)
    • VS Code at C:\Users\Amilkar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.2130]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 107.0.5304.87
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 107.0.1418.24

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by Hwan-seok** [comment] 2022-10-30 17:42
same issue here

**Comment by macortesn** [comment] 2022-10-30 19:11
Same here

**Comment by sebrojas14** [comment] 2022-10-30 19:46
Same here

**Comment by nathanielajayi7** [comment] 2022-10-30 20:10
Same here

**Comment by yaronwalterheylife** [comment] 2022-10-30 20:21
Same here
I fix it by changing to this
implementation 'com.facebook.android:facebook-android-sdk:15.0.1'

**Comment by sebrojas14** [comment] 2022-10-30 20:29
> 

where?

**Comment by sebrojas14** [comment] 2022-10-30 20:29
> Same here I fixed it by changing to this implementation 'com.facebook.android:facebook-android-sdk:15.0.1'

Where? @yaronwalterheylife

**Comment by alihuseyin** [comment] 2022-10-30 20:33
same

**Comment by yaronwalterheylife** [comment] 2022-10-30 20:34
android/build.gradle
line 44
in the plugin directory in your project
choose facebook_app_events-0.18.0 / or whatever version you use

**Comment by yaronwalterheylife** [comment] 2022-10-30 20:35
<img width="273" alt="Screen Shot 2022-10-30 at 22 34 54" src="https://user-images.githubusercontent.com/97390518/198900442-4ff726a1-e1a8-4c8a-8f7a-38f1f3e45849.png">
This is the location in my project

**Comment by yaronwalterheylife** [comment] 2022-10-30 21:09
Also on your build.gradle project file
check if you have this line and change it
implementation 'com.facebook.android:facebook-android-sdk:latest.release'

**Comment by umairali4433** [comment] 2022-10-31 00:32
Not working for me

**Comment by Hwan-seok** [comment] 2022-10-31 01:44
Use this until PR is merged
```yaml
  facebook_app_events: # ^0.18.0
    git: 
      url: https://github.com/Hwan-seok/flutter_facebook_app_events
      ref: fix/build-failed
```

**Comment by cmengler** [comment] 2022-10-31 01:54
I'm using Gradle 7.4 -- adding this to my projects `android/app/build.gradle` in the interim:

```gradle
dependencies {
    // ...
    implementation(group: 'com.facebook.android', name: 'facebook-android-sdk') {
        version {
            strictly '15.0.2'
        }
    }
}
```

**Comment by sivaprasadnk** [comment] 2022-10-31 06:20
> 

This worked for me. Thanks !

**Comment by xuxiaowei13** [comment] 2022-10-31 06:42
> 

Thanks! You saved our day!

**Comment by DennisAlund** [comment] 2022-10-31 06:44
Thank you for the heads up. We're looking into this right now. On principle, we prefer not to lock the version to a very specific release such as `15.0.2` as it is more likely to create issues with compatibility with other libraries such as Facebook login, if they have a different dependency. 

Keeping the dependency generic to `15.x` will allow for a version resolution that it compatible across plugins. 

But  first of all, I need to look into this issue that seems to be breaking for a lot of you.

**Comment by yaylaselcuk** [comment] 2022-10-31 09:04
https://github.com/oddbit/flutter_facebook_app_events/actions/runs/3359313609
Hello, thank you for quick resolution.
However, it seems like the workflow to publish it to pub.dev has failed. That's why we are not getting the fixed version.

**Comment by DennisAlund** [comment] 2022-11-01 00:17
@yaylaselcuk the workflow wasn't including any fix yet. We're yet to confirm what is the issue. That workflow is simply adding a test-build of the example app before releasing, so we can try to capture blockers that prevent building an app with the plugin.

**Comment by DennisAlund** [comment] 2022-11-01 00:18
I am unable to reproduce the issue

```
➜  flutter_facebook_app_events git:(develop) cd example 
➜  example git:(develop) flutter build apk
Running "flutter pub get" in example...                            280ms
 
Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Running Gradle task 'assembleRelease'...                           37.0s
✓  Built build/app/outputs/flutter-apk/app-release.apk (17.8MB).
➜  example git:(develop) flutter doctor -v
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.0 22A380 darwin-arm, locale en-US)
    • Flutter version 3.3.6 on channel stable at /Users/dennis/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (6 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/dennis/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/dennis/Library/Android/sdk
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F17a
    ! CocoaPods 1.10.1 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0 22A380 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
➜  example git:(develop) 
```

**Closed** 2022-11-01 00:44 UTC
Labels: bug🐞

**Comment by DennisAlund** [comment] 2022-11-01 00:59
Btw, all for your reference, in the issue description above, please note that you have dependency on `jcenter` which is deprecated.

Make a clean build and make sure you don't have any dependencies on `jcenter` that can cause conflict.

```
Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml.
> Could not HEAD 'https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/maven-metadata.xml'.
```
 - https://github.com/oddbit/flutter_facebook_app_events/pull/189
 - https://blog.gradle.org/jcenter-shutdown
 - https://stackoverflow.com/questions/66651640/jcenter-deprecation-impact-on-gradle-and-android
