### ISSUE TITLE
[Bug]: IOS Build Issue in 0.14.5

### ISSUE THREAD

**Issue by bhanuka96** [oddbit/flutter_facebook_app_events#169] opened 2021-11-18 17:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I got this issue when building the ios app.

```
flutter/.pub-cache/hosted/pub.dartlang.org/facebook_app_events-0.14.5/ios/Classes/SwiftFacebookAppEventsPlugin.swift:64:19: warning: 'clearUserData()' is deprecated: Class methods for setting user information are deprecated and will be removed in the next major release. Please use the instance method versions instead.
            AppEvents.clearUserData()
                      ^
    /Users/bhanukaisuru/dev/flutter/.pub-cache/hosted/pub.dartlang.org/facebook_app_events-0.14.5/ios/Classes/SwiftFacebookAppEventsPlugin.swift:79:25: warning: 'appID' is deprecated: `Settings.appID` is deprecated and will be removed in the next major release, please use `Settings.shared.appID` instead
            result(Settings.appID)
                            ^
    /Users/bhanukaisuru/dev/flutter/.pub-cache/hosted/pub.dartlang.org/facebook_app_events-0.14.5/ios/Classes/SwiftFacebookAppEventsPlugin.swift:92:98: error: cannot convert value of type '[String : Any]' to expected argument type '[AppEvents.ParameterName : Any]'
                AppEvents.logEvent(AppEvents.Name(eventName), valueToSum: valueToDouble, parameters: parameters)
                                                                                          ^
    /Users/bhanukaisuru/dev/flutter/.pub-cache/hosted/pub.dartlang.org/facebook_app_events-0.14.5/ios/Classes/SwiftFacebookAppEventsPlugin.swift:92:98: note: arguments to generic parameter 'Key' ('String' and 'AppEvents.ParameterName') are expected to be equal
                AppEvents.logEvent(AppEvents.Name(eventName), valueToSum: valueToDouble, parameters: parameters)
                                                                                          ^
    /Users/bhanukaisuru/dev/flutter/.pub-cache/hosted/pub.dartlang.org/facebook_app_events-0.14.5/ios/Classes/SwiftFacebookAppEventsPlugin.swift:94:71: error: cannot convert value of type '[String : Any]' to expected argument type '[AppEvents.ParameterName : Any]'
                AppEvents.logEvent(AppEvents.Name(eventName), parameters: parameters)
                                                                          ^
    /Users/bhanukaisuru/dev/flutter/.pub-cache/hosted/pub.dartlang.org/facebook_app_events-0.14.5/ios/Classes/SwiftFacebookAppEventsPlugin.swift:94:71: note: arguments to generic parameter 'Key' ('String' and 'AppEvents.ParameterName') are expected to be equal
                AppEvents.logEvent(AppEvents.Name(eventName), parameters: parameters)
                                                                          ^
    /Users/bhanukaisuru/dev/flutter/.pub-cache/hosted/pub.dartlang.org/facebook_app_events-0.14.5/ios/Classes/SwiftFacebookAppEventsPlugin.swift:121:18: warning: 'isAutoLogAppEventsEnabled' is deprecated: `Settings.isAutoLogAppEventsEnabled` is deprecated and will be removed in the next major release, please use `Settings.shared.isAutoLogAppEventsEnabled` instead
            Settings.isAutoLogAppEventsEnabled = enabled
                     ^
    /Users/bhanukaisuru/dev/flutter/.pub-cache/hosted/pub.dartlang.org/facebook_app_events-0.14.5/ios/Classes/SwiftFacebookAppEventsPlugin.swift:131:18: warning: 'setDataProcessingOptions(_:country:state:)' is deprecated: `Settings.setDataProcessingOptions(_:_:_:)` is deprecated and will be removed in the next major release, please use the `Settings.shared.setDataProcessingOptions(_:_:_:)` method to set the data processing options instead
            Settings.setDataProcessingOptions(modes, country: country, state: state)
                     ^
    /Users/bhanukaisuru/dev/flutter/.pub-cache/hosted/pub.dartlang.org/facebook_app_events-0.14.5/ios/Classes/SwiftFacebookAppEventsPlugin.swift:150:18: warning: 'setAdvertiserTrackingEnabled' is deprecated: `Settings.setAdvertiserTrackingEnabled(_:)` is deprecated and will be removed in the next major release, please use the `Settings.shared.isAdvertiserTrackingEnabled` property to set a value instead
            Settings.setAdvertiserTrackingEnabled(enabled)
                     ^
    /Users/bhanukaisuru/dev/flutter/.pub-cache/hosted/pub.dartlang.org/facebook_app_events-0.14.5/ios/Classes/SwiftFacebookAppEventsPlugin.swift:151:18: warning: 'isAdvertiserIDCollectionEnabled' is deprecated: `Settings.isAdvertiserIDCollectionEnabled` is deprecated and will be removed in the next major release, please use `Settings.shared.isAdvertiserIDCollectionEnabled` instead
            Settings.isAdvertiserIDCollectionEnabled = collectId
                     ^
    remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
```

### Expected Behavior

Build without any issue

### Flutter Doctor

```shell
Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale
    en-LK)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.2)
[✓] Connected device (2 available)
```
```

**Comment by bhanuka96** [comment] 2021-11-18 17:52
Temp solution to downgrade plugin to `0.12.0`

**Comment by DennisAlund** [comment] 2021-11-19 00:35
Duplicate of #159

**Closed by DennisAlund** 2021-11-19 00:35 UTC
Labels: bug🐞
