### ISSUE TITLE
[Bug]: Getting error after adding "facebook_app_events: ^0.14.8" into my project

### ISSUE THREAD

**Issue by sreeraj43** [oddbit/flutter_facebook_app_events#200] opened 2022-01-18 06:11 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Currently getting error while running the project
![appevents_issue](https://user-images.githubusercontent.com/55575396/149880466-1de09452-0024-48c7-9b88-4763b80b3f50.jpg)

### Expected Behavior

Need to run the project without errors

### Steps To Reproduce

1. Added facebook_app_events: ^0.14.8 in my pubspec.yaml
2. Executed "flutter pub get" and "flutter doctor" successfully
3. Then I tried to run the project and getting error, please find the attachment below
![appevents_issue](https://user-images.githubusercontent.com/55575396/149880551-78b88c91-8bd4-48e5-91d2-871ad7ec72ad.jpg)

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1466], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (3 available)
```

**Comment by ferysyukur** [comment] 2022-01-19 07:22
Hi @sreeraj43, I tried to reproduce that error and still couldn't get the error. I think it's because the server get error 502.
Please try to use `flutter clean` first and rerun the project.

**Comment by sreeraj43** [comment] 2022-01-19 07:28
Iam already run the flutter clean command successfully, but there is no use still getting the same error, please give me a solution for this

**Comment by ferysyukur** [comment] 2022-01-19 07:39
Could you upgrade your flutter ? 
- `flutter upgrade`
- `flutter clean`
- running the apps

**Comment by Ayman-Barghout** [comment] 2022-01-19 09:49
I am facing the same issue, when I specify the version of Facebook SDK in `build.gradle` to the latest `12.3.0` I don't get the error anymore and the app builds successfully.
I will open a PR.

**Comment by sreeraj43** [comment] 2022-01-27 07:00
@Ayman-Barghout still getting the same error after I added latest facebook SDK into my build.gradle

**Comment by Ayman-Barghout** [comment] 2022-01-27 09:13
@sreeraj43 the PR is not merged yet, you can use the package from GitHub until it gets merged, at least that's what we are doing.

In `pubspec.yaml`:
```yaml
  # FIX-ME: Switch to hosted dependency when PR https://github.com/oddbit/flutter_facebook_app_events/pull/201 is merged and published
  facebook_app_events:
    git: https://github.com/doneservices/flutter_facebook_app_events
```

**Comment by DennisAlund** [comment] 2022-01-31 02:28
Please see comments on PR #201

**Comment by DennisAlund** [comment] 2022-01-31 02:31
> I am facing the same issue, when I specify the version of Facebook SDK in `build.gradle` to the latest `12.3.0` I don't get the error anymore and the app builds successfully.

1. Please confirm what version your setup resolves to if you keep `12.+` as the current code is setup to do.
2. Please check if your code keeps working if you revert back your explicit `12.3.0` to `12.+` (then your repo dependency was just stuck on a version)
3. Please provide information about other Facebook depending plugins you are using

**Comment by Ayman-Barghout** [comment] 2022-01-31 08:58
> > I am facing the same issue, when I specify the version of Facebook SDK in `build.gradle` to the latest `12.3.0` I don't get the error anymore and the app builds successfully.
> 
> 1. Please confirm what version your setup resolves to if you keep `12.+` as the current code is setup to do.
> 2. Please check if your code keeps working if you revert back your explicit `12.3.0` to `12.+`. Then your repo dependency was likely stuck on a version... a clean build/install should also have helped
> 3. Please provide information about other Facebook depending plugins you are using

Thanks for the reply and interest.

1. It couldn't be resolved, I got a `Could not resolve com.facebook.android:facebook-android-sdk:12.+.`.
2. I checked and it fails everytime I use `12.+` instead of the explicit version. 
3. I am not currently using any Facebook-dependent plugins in my app aside from `facebook_app_events`.

**Comment by DennisAlund** [comment] 2022-01-31 09:04
It's better to keep a non-explicit version with major release range to make compatible with potential other plugins using the Facebook SDK.

Seems that it could be that the `12.+` version syntax isn't supported, should be [12.0,13.0)
https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN402

**Comment by Ayman-Barghout** [comment] 2022-02-01 07:34
> It's better to keep a non-explicit version with major release range to make compatible with potential other plugins using the Facebook SDK.
> 
> Seems that it could be that the `12.+` version syntax isn't supported, should be `[12.0,13.0)` [docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN402](https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN402)

For some reason even this syntax "`[12.0,13.0]`" doesn't work in my project, I will investigate further and reply to the comments on the PR soon - sorry, been busy since yesterday  -, also creating a new flutter project, it works perfectly with ^0.14.8, so it might be conflicting dependency or something else causing this but specifying a certain version fixes it, it'd be great if someone has a better idea of what might be causing this.

**Comment by Raziel619** [comment] 2022-03-09 20:33
Heya, I am also experiencing this issue on 0.15.0
**Could not resolve com.facebook.android:facebook-android-sdk:12.+.**

I've been using my own fork to mitigate this issue but would rather switch back to the official plugin

facebook_app_events:
    git:
      url: git://github.com/Raziel619/flutter_facebook_app_events
      ref: develop

**Comment by DennisAlund** [comment] 2022-04-20 00:28
At the moment of writing the current version is 0.16. Please update your version and open the issue again if the problem is still around.

**Closed by DennisAlund** 2022-04-20 00:28 UTC
Labels: bug🐞
