### ISSUE TITLE
logPurchase event

### ISSUE THREAD

**Issue by shubhanshusingh** [oddbit/flutter_facebook_app_events#36] opened 2020-06-30 11:31 UTC
## Expected Behavior

    facebookAppEvents.logPurchase(currency: "INR", amount: value);

## Current Behavior

 NA
## Possible Solution

```
Future<void> logPurchase({
    String currency,
    double amount,
  }) {
    final args = <String, dynamic>{
      'currency': currency,
      'purchaseAmount': amount
    };

    return _channel.invokeMethod<void>('logPurchase', _filterOutNulls(args));
  }

```
## Context

if we want to add external purchase, this will alllow us to log.
## Your Environment
* Output from `flutter doctor`
* Operating System and version:

**Comment by DennisAlund** [comment] 2020-07-03 02:35
Thank you for the suggestion, I think this is the same as mentioned in issue #16 and the proposed solution is currently just showing the dart API implementation. It would need to also outline the native platform implementations to be a full solution.  

I would appreciate and be happy to review a pull request for it.

I'll close this one as a duplicate of #16 and we can proceed the discussion there.

**Closed by DennisAlund** 2020-07-03 02:35 UTC

**Comment by AtixD** [comment] 2020-08-24 20:23
#50
